name: baxi_app
description: Baxi client app

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.19.2
  firebase_messaging: ^12.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^9.7.0
  get: ^4.6.5
  getwidget: ^3.0.1
  http: ^0.13.4
  intl: ^0.17.0
  loader_overlay: ^2.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
